name: Build, Push and Securize

on:
  workflow_dispatch:

jobs:

  check-credentials:
    runs-on: ubuntu-latest
    outputs:
      credentials_available: ${{ steps.check.outputs.credentials_available }}
    steps:
      - name: Check registry username/password defined
        id: check
        run: |
          if [ -z "${{ secrets.HARBOR_PASSWORD }}" ] || [ -z "${{ vars.HARBOR_USERNAME }}" ]; then
            echo "credentials_available=false" >> $GITHUB_OUTPUT
          else
            echo "credentials_available=true" >> $GITHUB_OUTPUT
          fi
          
  build-push:
    runs-on: ubuntu-latest
    needs: check-credentials
    permissions:
      id-token: write
      contents: read
      attestations: write
    env:
      IMAGE_NAME: gophers-api
      HARBOR_REGISTRY: 79352h8v.c1.de1.container-registry.ovh.net
    steps:
      - uses: actions/checkout@v4

      - name: Login to Harbor
        if: needs.check-credentials.outputs.credentials_available == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.HARBOR_REGISTRY }}
          username: ${{ vars.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push to Harbor
        id: build-and-push-harbor
        if: needs.check-credentials.outputs.credentials_available == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          sbom: true
          push: true
          tags: ${{ env.HARBOR_REGISTRY }}/auto/${{ env.IMAGE_NAME }}:latest

      - name: Attest
        if: needs.check-credentials.outputs.credentials_available == 'true'
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.HARBOR_REGISTRY }}/auto/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build-and-push-harbor.outputs.digest }}
          push-to-registry: true
